In [1]:
import numpy as np

# Create a numpy array with patient data and attributes
patient_data = np.array([[76,126,38.0],
                         [74,120,38.0],
                         [72,118,37.5],
                         [78,136,37.0]])
                         
print(patient_data)
# Calculate pairwise Euclidean distances
distances = np.sqrt(np.sum((patient_data[:, np.newaxis] - patient_data) ** 2, axis=2))

# Find the indices of the furthest and nearest patients
furthest_patient = np.argmax(np.sum(distances, axis=1))
print(furthest_patient)
nearest_patient = np.argsort(distances, axis=1)[:2]
print(nearest_patient)

# Add a dummy person
dummy_person = np.array([13, 14, 15.0])
patient_data = np.vstack((patient_data, dummy_person))

# Recalculate distances with the dummy person
distances = np.sqrt(np.sum((patient_data[:, np.newaxis] - patient_data) ** 2, axis=2))

# Find the index of the closest patient to the dummy person
closest_patient = np.argmin(distances[-1])
print(closest_patient)

[[ 76.  126.   38. ]
 [ 74.  120.   38. ]
 [ 72.  118.   37.5]
 [ 78.  136.   37. ]]
3
[[0 1 2 3]
 [1 2 0 3]]
4
